version: "3.8"

name: bd

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:latest
    restart: always
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
